services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee_app
    container_name: employee_app_container
    ports:
      - "8080:8080"   # Porta do host : Porta do container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employee_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_employee
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
