services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee_app
    container_name: employee_app_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:root123@mongodb:27017/employee_db?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb_employee
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: employee_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:1
    container_name: mongo_express_employee
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123

volumes:
  mongodb_data:
